# Generated by Django 4.0.4 on 2023-06-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='telefono'),
        ),
    ]
