# Generated by Django 4.0.4 on 2023-06-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0002_alter_userprofile_direccion_alter_userprofile_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='direccion'),
        ),
    ]
